config/routes.rb
Homegame::Application.routes.draw do
  root :to => "main#index"

  match "/about", to: "about#index", :as => "about"
  match '/unvote/:id', to: 'votes#update', :via => :put, :as => "unvote"
  match '/about', to: 'about#index'
  match '/register', to: 'players#new'
  match '/login', to: 'sessions#new'
  match '/logout', to: 'sessions#destroy'

  resources :players
  resources :sessions
  resources :games
  resources :votes
  resources :about
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @player = Player.new
    @vote = Vote.new
    @current_player_vote = Vote.first(:conditions => ["player_id = ? AND week_number = ? AND is_playing = true", session[:player_id], upcoming_week_number])
    @votes = Vote.all
  end

  def upcoming_week_number
    week_number = Date.current.next_week.strftime("%W")
  end
end

app/views/main/index.html.haml
%section.row.content.home
  .hero-unit
    %h2
      Ladies and Gents,

    -if enough_votes?
      %p
        <strong><em>Whoo buddy!</em></strong> It looks like we got ourselves a game for
        %span.label.label-important= current_game_date
    -else
      %p
        Unfortunately, <strong><em>no game so far</em></strong>; not enough folks have voted on a date for the
        %strong= "week of #{game_week_date}."
      %p
        <em>However</em>, there are still
        %strong= (10 - current_vote_count) unless current_vote_count >= 10
        spots left, and we only need
        %strong= (6 - current_vote_count) unless current_vote_count >= 6
        more to have a decent game.

    =link_to 'More Info', about_path, :class => "btn btn-inverse btn-large"

  .meat_and_potatoes
    -if current_player
      =render :partial => "common/vote_form"
    -else
      =render :partial => "common/login"

    =render :partial => "common/vote_results", :locals => {:votes => @votes}

    =render :partial => "common/chat" unless !current_player