config/routes.rb
Homegame::Application.routes.draw do
  root :to => "main#index"

  match "/about", to: "about#index", :as => "about"
  match '/unvote/:id', to: 'votes#update', :via => :put, :as => "unvote"
  match '/about', to: 'about#index'
  match '/register', to: 'players#new'
  match '/login', to: 'sessions#new'
  match '/logout', to: 'sessions#destroy'

  resources :players
  resources :sessions
  resources :games
  resources :votes
  resources :about
end

app/views/common/_login.html.haml
.login_form
  %h3 Log in and help pick the game day

  = twitter_bootstrap_form_for :session, :url => sessions_path, :role => "form" do |f|
    = f.inputs 'Note: All fields are required.' do
      = f.text_field :username, :required => true, :placeholder => "username"
      = f.password_field :password, :required => true, :placeholder => "password"
      = f.submit 'Log in', :class => "btn btn-success"
      %span.alt-action
        Not registered?
        = link_to "Sign up!", register_path

app/views/common/_notifications.html.haml
- unless flash.empty?
  %section.alert-block
    %a.close{:data => {:dismiss => "alert"}} &#215;
    - unless flash[:notice].blank?
      .alert.alert-success
        = content_tag :div, flash[:notice]

    - unless flash[:error].blank?
      .alert.alert-error
        = content_tag :div, flash[:error]

    - unless flash[:alert].blank?
      .alert.alert-warning
        = content_tag :div, flash[:alert]

app/views/common/_player_utils.html.haml
- if current_player
  %dl.span3
    %dt
      Welcome,
      %strong= current_player.first_name.capitalize
    / -if current_player.username == "megalithic"
    /   %dd
    /     =link_to "Add game", {:controller => "games", :action => "new"}
    %dd
      =link_to "Log out", {:controller => "sessions", :action => "destroy"}

app/views/common/_register.html.haml
%section.row.content
  .meat_and_potatoes
    .register_form
      %h3 You want to win some money right?<br /><small>Well, get to registering then!</small>

      = twitter_bootstrap_form_for @player, :class => "form-inline" do |f|
        = f.inputs "Note: All fields are required", :class => "form-inline" do
          = f.text_field :first_name, :required => true, :placeholder => "First Name"
          = f.text_field :last_name, :required => true, :placeholder => "Last Name"
          = f.text_field :username, :required => true, :placeholder => "Username"
          = f.email_field :email, :required => true, :placeholder => "me@example.com"
          = f.password_field :password, :required => true
          = f.password_field :password_confirmation, :required => true
        = f.actions do
          = f.submit 'Register', :class => "btn btn-success"
          %span.alt-action
            Already registered?
            = link_to "Log in!", root_url

app/views/common/_vote_form.html.haml
.vote_form
  - if !player_voted? && !is_playing?
    %h3 Get your vote in..
    = twitter_bootstrap_form_for @vote, :html => {:role => "form"} do |f|
      = f.inputs "Note: You're only allowed one vote per week." do
        = f.select :selected_date, '', game_week_options, :required => true, :include_blank => true
        = f.submit "Vote!", :class => "btn btn-success form-inline"
  - elsif player_voted? && is_playing?
    %h3 Your seat has been reserved..
    %aside
      %p.important
        Your vote is in for the
        %strong
          %em
            week of
            = game_week_date
        %i.icon-arrow-right
      %p.well
        %i.icon-info-sign
        <strong>Can't play on the majority voted day?</strong>
        %span
          You can
          = link_to 'sit out this time', unvote_path(@current_player_vote), :method => :put
  - else
    %h3 Sorry you can't make it this time
    %aside
      %p.important Be sure to vote again for the next home game

app/views/common/_vote_results.html.haml
%section.vote_results
  %h3
    Results for the week of
    =game_week_date

  %aside
    - if !player_voted? && !is_playing?
      %p You want to play? Well then, register, log in and <strong>pick a day!</strong>

    - if current_vote_count > 0
      %h4
        We've got
        =pluralize(current_vote_count, 'seat')
        reserved so far:
    - else
      %h4
        Be the first to reserve your seat.

    - unless !@votes.any?
      %ul
        - @votes.each do |vote|
          %li{:id => vote.player_id == session[:player_id] ? "my_vote" : ""}
            - unless current_vote_count < 1
              - if (vote.player_id == session[:player_id])
                = link_to unvote_path(vote), :method => :put, :class => "remove" do
                  %i.icon-remove
                = link_to unvote_path(vote), :method => :put, :rel => "tooltip", :title => "Sit out for this game" do
                  - full_name = player_by_id(vote.player_id).full_name
                  = abbr_full_name(full_name) unless full_name.nil?
                  wants to play on
                  = vote.selected_date.strftime("%A (%b. #{vote.selected_date.day.ordinalize})") unless vote.selected_date.nil?
              - else
                %i.icon-ok
                %span
                  - full_name = player_by_id(vote.player_id).full_name
                  = abbr_full_name(full_name) unless full_name.nil?
                  wants to play on
                  = vote.selected_date.strftime("%A (%b. #{vote.selected_date.day.ordinalize})") unless vote.selected_date.nil?